services:

  plate_recognition:
    image: transport_recognition
    container_name: transport_recognition
    environment:
      - VIDEO_PATH=http://104.207.27.126:8080/mjpg/video.mjpg
      #Режим съемки, возможные значения - 1 (вблизи) и 2 (издалека)
      - SHOOTING_MODE=2
      #Область через которую должны проходить транспортные средства для их обнаружения
      #Может быть только фигурой, координаты задаются относительно велечин w (ширина кадра) и h (высота кадра)
      #Если формат некорректный, захватывается вся область кадра (не рекомендуется)
      - REGION_OF_TRANSPORT_DETECTION=whole_image
      #Область через которую должны проходить транспортные средства для подсчета их количества
      #Может быть линией или фигурой, координаты задаются относительно велечин w (ширина кадра) и h (высота кадра) и числами
      #Если формат некорректный, захватывается вся область кадра (не рекомендуется)
      - REGION_OF_COUNTING=[(w * 0, h // 2), (w * 1, h // 2), (w * 0.5, h * 0.67), (0,  h * 0.8)]
      #Область через которую должны проходить транспортные средства для обнаружения их номеров
      #Может быть только фигурой, координаты задаются относительно велечин w (ширина кадра) и h (высота кадра)
      #Если формат некорректный, захватывается вся область кадра (не рекомендуется)
      - REGION_OF_PLATES_DETECTION=whole_image

      #Хост и порт для подключения к базе данных
      - HOST=clickhouse-server
      - PORT=9000
      #Хост и порт для GRPC
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=1539
    ports:
      - "6000:1539"

  clickhouse-server:
    image: bitnami/clickhouse:latest
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_ADMIN_PASSWORD=password
    ports:
      - "7500:8123"
      - "8500:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: