# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehicle_data.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'vehicle_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12vehicle_data.proto\x12\x0cvehicle_data\"1\n\tTimeRange\x12\x12\n\nstart_time\x18\x01 \x01(\x05\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\x05\"%\n\x05Plate\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x05\"\x9f\x01\n\rTransportData\x12\x18\n\x10total_count_cars\x18\x01 \x01(\x05\x12\x19\n\x11total_count_buses\x18\x02 \x01(\x05\x12\x1a\n\x12total_count_trucks\x18\x03 \x01(\x05\x12\x1f\n\x17total_count_motorcycles\x18\x04 \x01(\x05\x12\x1c\n\x14total_count_bicycles\x18\x05 \x01(\x05\"1\n\nPlatesData\x12#\n\x06plates\x18\x01 \x03(\x0b\x32\x13.vehicle_data.Plate2\\\n\x10ServiceTransport\x12H\n\x10GetTransportData\x12\x17.vehicle_data.TimeRange\x1a\x1b.vehicle_data.TransportData2S\n\rServicePlates\x12\x42\n\rGetPlatesData\x12\x17.vehicle_data.TimeRange\x1a\x18.vehicle_data.PlatesDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TIMERANGE']._serialized_start=36
  _globals['_TIMERANGE']._serialized_end=85
  _globals['_PLATE']._serialized_start=87
  _globals['_PLATE']._serialized_end=124
  _globals['_TRANSPORTDATA']._serialized_start=127
  _globals['_TRANSPORTDATA']._serialized_end=286
  _globals['_PLATESDATA']._serialized_start=288
  _globals['_PLATESDATA']._serialized_end=337
  _globals['_SERVICETRANSPORT']._serialized_start=339
  _globals['_SERVICETRANSPORT']._serialized_end=431
  _globals['_SERVICEPLATES']._serialized_start=433
  _globals['_SERVICEPLATES']._serialized_end=516
# @@protoc_insertion_point(module_scope)
